name: Checkov (compliance)

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkov:
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: FelipeFuhr/ffreis-workflows-terraform/.github/workflows/tf-checkov.yml@1b59a920b1b4b226f3e5a91eb9042827b9c435cb
    with:
      scan-directory: "."
