name: Checkov (compliance)

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkov:
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: ffreis-org/ffreis-workflows-terraform/.github/workflows/tf-checkov.yml@5606584d4d99f3f0886517c4e637aa0b19308898 # v1.1.3
    with:
      scan-directory: "."
