name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semantic-pr:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@510fa18cb916d2fe30251e4fae2726335028d5fa

  actionlint:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@c3e3e0a44d4b79697f1babaa9bf287d1b264da52
    with:
      working-directory: "."

  labeler:
    if: github.event_name == 'pull_request_target'
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-labeler.yml@c3e3e0a44d4b79697f1babaa9bf287d1b264da52
    with:
      rules-json: |-
        [
          {"label":"ci","patterns":[".github/workflows/**",".github/actions/**"]},
          {"label":"terraform","patterns":["**/*.tf","modules/**","examples/**"]},
          {"label":"docs","patterns":["**/*.md"]}
        ]
