name: Terraform Docs (drift check)

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "modules/**"
      - ".github/workflows/tf-docs.yml"
  merge_group:
    types: [checks_requested]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-terraform/.github/workflows/tf-docs.yml@5606584d4d99f3f0886517c4e637aa0b19308898 # v1.1.3
    with:
      working-directory: "modules"
